"""Initial governed rate registry

Revision ID: b337da080f79
Revises:
Create Date: 2026-09-07 19:46:23.634901

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b337da080f79"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("mimetype", sa.String(length=100), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('admin','editor','reviewer','viewer')", name="user_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "rate_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("rate_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rate_records_archived"), ["archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_rate_records_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "rate_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("granted", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("sql_note", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("data_type", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("rows", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=True),
        sa.Column("change_reason", sa.String(length=1000), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("review_note", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("data_type IN ('table','document')", name="revision_type"),
        sa.CheckConstraint(
            "state IN ('draft','submitted','approved','rejected')", name="revision_state"
        ),
        sa.CheckConstraint(
            "unit IN ('probability','percent','per_thousand')", name="revision_unit"
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from", name="revision_dates"
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name="revision_priority"),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["rate_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "number", name="revision_number"),
    )
    with op.batch_alter_table("rate_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rate_revisions_record_id"), ["record_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rate_revisions_state"), ["state"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("revision_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["rate_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["rate_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_record_id"), ["record_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_record_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("rate_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_revisions_state"))
        batch_op.drop_index(batch_op.f("ix_rate_revisions_record_id"))

    op.drop_table("rate_revisions")
    with op.batch_alter_table("rate_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_records_owner_id"))
        batch_op.drop_index(batch_op.f("ix_rate_records_archived"))

    op.drop_table("rate_records")
    op.drop_table("users")
    op.drop_table("attachments")
    # ### end Alembic commands ###
